name: audio_engine_example
description: Example app for audio_engine plugin.

publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_engine:
    path: ../
  file_picker: ^8.0.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.6

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
